# FROM webstreamer/nvm-py2-gcc54:0.1
FROM conanio/gcc54:1.12.2

LABEL maintainer="Mingyi Zhang <mingyi.z@outlook.com>"


RUN wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash \
    && echo ================ \
    && echo $NVM_DIR \
    && echo ================ \
    && nvm --version


